// <auto-generated />
using System;
using CrazyBooks_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrazyBooks_DataAccess.Migrations
{
    [DbContext(typeof(CrazyBooksDbContext))]
    [Migration("20220619162532_Initiale")]
    partial class Initiale
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrazyBooks_Models.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorDetail_Id")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorDetail_Id")
                        .IsUnique()
                        .HasFilter("[AuthorDetail_Id] IS NOT NULL");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorDetail_Id = 1,
                            FirstName = "Agatha",
                            LastName = "Christie"
                        },
                        new
                        {
                            Id = 2,
                            AuthorDetail_Id = 2,
                            FirstName = "Bernard",
                            LastName = "Turgeon"
                        },
                        new
                        {
                            Id = 3,
                            AuthorDetail_Id = 3,
                            FirstName = "Dominique",
                            LastName = "Lamaute"
                        },
                        new
                        {
                            Id = 4,
                            AuthorDetail_Id = 4,
                            FirstName = "Vincent",
                            LastName = "Founier-Boivert"
                        },
                        new
                        {
                            Id = 5,
                            AuthorDetail_Id = 5,
                            FirstName = "Kim",
                            LastName = "Messier"
                        },
                        new
                        {
                            Id = 6,
                            AuthorDetail_Id = 6,
                            FirstName = "Guy",
                            LastName = "Bergeron"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Elie",
                            LastName = "Hanson"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Agatha",
                            LastName = "Christie"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Josh",
                            LastName = "Malerman"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Julie",
                            LastName = "Laganière"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Hugues",
                            LastName = "Chassé"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Insaf Ben",
                            LastName = "Kadni"
                        },
                        new
                        {
                            Id = 13,
                            AuthorDetail_Id = 7,
                            FirstName = "Josh",
                            LastName = "Malerman"
                        });
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.AuthorBook", b =>
                {
                    b.Property<int>("Author_Id")
                        .HasColumnType("int");

                    b.Property<int>("Book_Id")
                        .HasColumnType("int");

                    b.Property<int>("PCRoyalties")
                        .HasColumnType("int");

                    b.HasKey("Author_Id", "Book_Id");

                    b.HasIndex("Book_Id");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            Author_Id = 1,
                            Book_Id = 1,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 13,
                            Book_Id = 2,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 6,
                            Book_Id = 3,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 6,
                            Book_Id = 4,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 6,
                            Book_Id = 5,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 1,
                            Book_Id = 6,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 13,
                            Book_Id = 7,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 7,
                            Book_Id = 8,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 4,
                            Book_Id = 9,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 5,
                            Book_Id = 10,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 6,
                            Book_Id = 11,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 7,
                            Book_Id = 12,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 1,
                            Book_Id = 13,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 1,
                            Book_Id = 14,
                            PCRoyalties = 100
                        },
                        new
                        {
                            Author_Id = 2,
                            Book_Id = 15,
                            PCRoyalties = 60
                        },
                        new
                        {
                            Author_Id = 3,
                            Book_Id = 15,
                            PCRoyalties = 40
                        });
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.AuthorDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Photo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("AuthorDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Agatha Christie est sans nul doute l'une des romancières les plus appréciées de son temps. Auteure de quatre-vingt-quatre ouvrages qui constituent pour la plupart des intrigues policières, d'une vingtaine de pièces de théâtre et de plusieurs recueils de nouvelles, elle est parvenue à faire de ses oeuvres de grands succès du XXe siècle, lues partout dans le monde (plus de 2 milliards d'exemplaires vendus).",
                            Photo = ""
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Auteur de plusieurs ouvrages portant sur l’administration, la gestion des ressources humaines, l’informatique et le commerce électronique, Bernard Turgeon a obtenu le Prix du ministre de l’Éducation(1982), deux mentions(1987, 2000) et un prix d’encouragement(1985).Titulaire d’un baccalauréat en administration et d’une licence en sciences commerciales, il enseigne le management et la gestion des ressources humaines au Cégep Édouard - Montpetit",
                            Photo = ""
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Docteur en relations industrielles, Dominique Lamaute enseigne au département des Techniques administratives du Cégep de Saint-Hyacinthe. Auteur d’ouvrages sur le management, la gestion des ressources humaines et l’entreprise, il a obtenu une mention au Prix du ministre de l’Éducation (2000). Spécialisé en gestion stratégique des ressources humaines, Dominique Lamaute est appelé à prononcer plusieurs conférences sur l’évolution des modèles de gestion des ressources humaines et sur le talent management.",
                            Photo = ""
                        },
                        new
                        {
                            Id = 4,
                            Biography = "musicien et enseignant. Il a joué pour Cavalia et dans des groupes de trad, de free jazz et de black métal. 'Le puits' (2020) est son premier roman.",
                            Photo = ""
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Kim Messier enseigne le français à l'école secondaire du Verbe Divin, à Granby, où elle habite. En publiant son premier roman aux Éditions de Mortagne, cette enseignante réalise le plus grand rêve de sa vie ! Le récit de Léa s'est imposé à elle en 2008, lors d'un congé de maternité. Depuis, c'est l'avalanche ! Les idées s'enchaînent, les mots surgissent et Kim ne rêve plus que d'une chose : écrire à temps plein.",
                            Photo = ""
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Né le31 août 1964, est un écrivain québécois spécialisé en fantastique et fantasy. Son premier roman, L'Orbe et le Croissant, est publié par les Éditions Arion en 2006.Les Éditions Porte Bonheur l'ont réédité, puis édité les deux tomes suivants formant La Trilogie de L'Orbe.Il a ensuite écrit une deuxième trilogie L'héritière de Ferrolia en 2010. Auteur prolifique, il a ensuite publié Cœur de givre en avril 2011 et poursuivi avec une incursion dans le monde de la science-fiction en livrant un tome de la série des Clowns vengeurs, Valse macabre avril 2012. Sa dernière œuvre, Les âmes perdues, est parue en novembre 2012.",
                            Photo = ""
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Josh Malerman est le chanteur et le parolier du groupe de rock The High Strung. 'Bird Box', son premier roman a remporté le Michigan Notable Book Award. Il habite à Ferndale dans le Michigan.",
                            Photo = ""
                        });
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Promo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Publisher_Id")
                        .HasColumnType("int");

                    b.Property<string>("Resume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Subject_Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Publisher_Id");

                    b.HasIndex("Subject_Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            ISBN = "9782253167129",
                            Price = 22m,
                            Promo = false,
                            PublishedDate = new DateTime(1920, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 1,
                            Resume = "Qui avait intérêt à assassiner Mrs Ingelthorp, la richissime propriétaire du domaine de Styles? Pratiquement tous ceux qui l’entouraient. Qui est le coupable idéal ? Le second et jeune mari de la victime… ",
                            Subject_Id = 1,
                            Title = "Affaires de famille"
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            ISBN = "9782253183839",
                            Price = 14m,
                            Promo = true,
                            PublishedDate = new DateTime(2019, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 3,
                            Resume = "Malorie et ses enfants sont barricadés chez eux. Dehors, il y a un danger terrible. Ils ne peuvent sortir que les yeux bandés pour rester en vie. Mais le temps est compté, alors Malorie décide de réveiller ses enfants afin de partir à la recherche d'une hypothétique colonie de survivants. Premier roman.",
                            Subject_Id = 7,
                            Title = "BirdBox"
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            ISBN = "9782897655013",
                            Price = 20m,
                            Promo = false,
                            PublishedDate = new DateTime(2020, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 3,
                            Resume = "Dans le panthéon des divinités d’Arménis, la discorde règne. La Dame Blanche, mère de tous les dieux, décide de noyer le monde sous un déluge. Les humains comme les dieux seront soumis à différentes épreuves. Servia et Keiko porteront ce poids pour les humains à leur insu. Servia, toujours accompagné de Keiko, tentera de percer les mystères de son passé.",
                            Subject_Id = 6,
                            Title = "Ldame Blanche"
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            ISBN = "9782897655044",
                            Price = 22m,
                            Promo = false,
                            PublishedDate = new DateTime(1921, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 3,
                            Resume = "La Dame Blanche charge Servia et Keiko de mettre sur pied une organisation pour maintenir l’équilibre sur Arménis, l’Ordre de l’épervier. Devenue reine malgré elle, Servia devra se préparer à une guerre dont l’issue est incertaine. Quelques années plus tard, les héros seront conviés à une mission ultime dont le résultat bouleversera tout, même les dieux.",
                            Subject_Id = 6,
                            Title = "Le règne de l'épervier"
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            ISBN = "9782923898902",
                            Price = 10m,
                            Promo = true,
                            PublishedDate = new DateTime(2014, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 3,
                            Resume = "Culcuth, dieu de la mort, fomente en secret un plan visant à contrôler l’ensemble de l’humanité afin d’augmenter son pouvoir. Il crée le Portail des ombres, d’où s’échappent ses créatures. Pendant ce temps, au royaume de Ferrolia, Miranda est atteinte dès sa naissance d’une grave maladie qui provoque des crises incontrôlables. Son père, un roi despote, tente de la sacrifier afin de regagner la faveur des dieux. Elle sera sauvée par Torkil, un garde de la reine qui l’élèvera loin de Ferrolia. Âgée d’environ douze ans, Miranda que l’on nomme maintenant Servia afin de dissimuler son identité, perd Torkil qui meurt suite à une attaque à sa maison, avant qu’il ait pu lui dévoiler ses origines. Aidée d’un ami nommé Keiko qui possède la faculté de se changer en ours, elle tentera de trouver un ermite qui pourrait peut-être la guérir des crises qui la terrassent toujours. Mais Thamir l’ermite ne parvient pas à la guérir. Avec lui, ils se retrouveront tout près du Portail des Ombres et ils devront combattre les créatures de Culcuth qui ont commencé à envahir la région. Ils rencontreront un peuple au physique d’enfants, mais qui est puissant en magie, les Juventis. Les trois compagnons sont faits prisonniers et Culcuth force Thamir à devenir son héraut. Servia et Keiko parviendront à s’échapper avec l’aide des Juventis et de Thamir qui résistera au dieu, mais se sacrifiera afin de détruire le Portail des Ombres.",
                            Subject_Id = 6,
                            Title = "Le portail des ombres"
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            ISBN = "9782253241782",
                            Price = 10m,
                            Promo = false,
                            PublishedDate = new DateTime(1921, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 1,
                            Resume = "Les dix invités sont arrivés sur l'île du Nègre, mais rien ne semble normal : leur hôte est absent et quelqu'un a déposé dans leur chambre une comptine intitulée Les dix petits Nègres. Tout bascule quand une voix accuse chacun des invités d'un crime.",
                            Subject_Id = 1,
                            Title = "Ils étaient dix"
                        },
                        new
                        {
                            Id = 7,
                            Available = true,
                            ISBN = "9782253241782",
                            Price = 12m,
                            Promo = true,
                            PublishedDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 1,
                            Resume = "Les dix invités sont arrivés sur l'île du Nègre, mais rien ne semble normal : leur hôte est absent et quelqu'un a déposé dans leur chambre une comptine intitulée Les dix petits Nègres. Tout bascule quand une voix accuse chacun des invités d'un crime.",
                            Subject_Id = 1,
                            Title = "Inspection"
                        },
                        new
                        {
                            Id = 8,
                            Available = true,
                            ISBN = "99782896389100",
                            Price = 20m,
                            Promo = false,
                            PublishedDate = new DateTime(2021, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 3,
                            Resume = "Alain, un artiste peintre québécois, tombe un jour sur le vieux et mystérieux carnet de souvenirs de son grand-oncle Henri. Celui-ci, interné depuis son retour de France, où il avait assisté en tant que jeune soldat aux horreurs de la Première Guerre mondiale, semblait depuis longtemps porter un lourd secret sur ses épaules. Alain décide donc d’en savoir plus sur ces écrits troublants.Son enquête le mène en France,où il fera la connaissance d’un conférencier écossais un peu farfelu qui semble avancer les mêmes élucubrations que Henri.S’agit - il d’une pure fabulation, ou bien existe - t - il un lien entre ces deux témoignages ??",
                            Subject_Id = 6,
                            Title = "Le carnet maudit"
                        },
                        new
                        {
                            Id = 9,
                            Available = true,
                            ISBN = "9782898190001",
                            Price = 20m,
                            Promo = false,
                            PublishedDate = new DateTime(2020, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 3,
                            Resume = "Saint-Hyacinthe, 1996 Une vache est retrouvée décapitée près d'un puits. La sous-lieutenant Monique Demers et son patron Réal Rondeau, inspecteur bougon à deux doigts du divorce, sont en charge du singulier dossier. L'enquête, d'abord banale, débouche sur la disparition du fils du propriétaire de l'animal. Rondeau peine à démêler les fils de l'histoire. Pourquoi y a-t-il une quantité astronomique de PCP dans l'estomac de la vache étêtée? Et quel est le lien entre le jeune disparu et le réseau de revente de stupéfiants oeuvrant tout près de la polyvalente de la ville? Un roman policier prenant qui explore les vices les plus obscurs d'un coin de province moins tranquille qu'il en a l'air...",
                            Subject_Id = 1,
                            Title = "Le puits"
                        },
                        new
                        {
                            Id = 10,
                            Available = false,
                            ISBN = "9782898032813",
                            Price = 21m,
                            Promo = true,
                            PublishedDate = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 3,
                            Resume = "Mi-Panthère des neiges, mi-homme, Uncia est une Anomalie, un descendant des êtres humains ayant subi des expérimentations génétiques. Élevé dans le plus grand des secrets par les Adoratrices d’Odi, le menvatt à la canne au pommeau d’or accomplit maintes missions pour le compte des moniales, recluses dans le Grand Nord. Lorsqu’il se voit confier la mission d’éliminer une scientifique qui teste ses expériences sur le marché noir, Uncia découvre que cette femme détient la clé pour effectuer de nouvelles modifications génétiques capables de mettre fin à la domination des Arcurides et au système de castes. Pour exploiter sa découverte et la protéger, l’Anomalie entraîne sa cible chez les moniales. Marqué par des années d’exclusion et d’obéissance, Uncia se liera pour la première fois de sa vie à une femelle, dont il devra assurer la protection lorsqu’elle se retrouvera à la tête d’une rébellion de masse contre le Gouvernement légitime.",
                            Subject_Id = 2,
                            Title = "Uncia"
                        },
                        new
                        {
                            Id = 11,
                            Available = true,
                            ISBN = "9782898032752",
                            Price = 20m,
                            Promo = false,
                            PublishedDate = new DateTime(2019, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 3,
                            Resume = "Le Menvatt tourna une petite clé située sur le côté de la boîte avant de la poser au sol et d’en ouvrir le couvercle. Une musique triste se mit à résonner dans la pièce, et au centre de la boîte, la figurine d’une ballerine entièrement vêtue de blanc tournoyait au bras d’un clown multicolore. Jordan pencha la tête de côté, fredonnant la mélodie. Il se pencha de nouveau au-dessus de son sac, d’où il sortit une paire de pinces robustes au bout pointu. Mercado fronça les sourcils. Les menvatts ne faisaient pas dans la dentelle. Ils tuaient, appliquaient la vengeance sans perdre de temps. Pourquoi alors cette paire de pinces? Dans la Quadri-métropole aux prises avec des luttes politiques, les arcurides du Gouvernement Légitime pourchassent sans relâche les Odi-Menvatts, alors qu’un dangereux psychopathe s’est glissé parmi eux…",
                            Subject_Id = 2,
                            Title = "Valse macabre"
                        },
                        new
                        {
                            Id = 12,
                            Available = true,
                            ISBN = "9782898190063",
                            Price = 20m,
                            Promo = true,
                            PublishedDate = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 3,
                            Resume = "Alain Thibault, éminent conférencier du paranormal, est approché par une mystérieuse organisation pour participer à une expédition dans l'Arctique. Sous la menace des responsables de l'institution, il est contraint d'accepter de partir dans le Grand Nord canadien. Pourquoi la participation d'Alain est-elle essentielle pour les membres de cette mission ? Quels dangers guettent les participants de l'expédition Mirage ? Que cherche cette énigmatique agence au-delà du 82e parallèle ? Lorsque l'expédition découvre une base souterraine construite par les nazis durant la Deuxième Guerre mondiale, Alain comprend qu'on ne lui a vraiment pas tout dit... Un thriller fantastique haletant nous transportant aux confins de l'Arctique, abri sauvage et méconnu de très anciens secrets...",
                            Subject_Id = 1,
                            Title = "Mission Arctik"
                        },
                        new
                        {
                            Id = 13,
                            Available = false,
                            ISBN = "2253079391",
                            Price = 12m,
                            Promo = false,
                            PublishedDate = new DateTime(1937, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 1,
                            Resume = "La séduisante Linnet Ridgeway est retrouvée tuée d'une balle dans la tête lors d'une croisière sur le Nil. Chacun des passagers ayant au moins une bonne raison d'avoir assassiné la riche Américaine, l'enquête n'en est que plus difficile pour le célèbre détective belge Hercule Poirot.",
                            Subject_Id = 1,
                            Title = "Mort sur le Nil"
                        },
                        new
                        {
                            Id = 14,
                            Available = false,
                            ISBN = "9782253258032",
                            Price = 13m,
                            Promo = false,
                            PublishedDate = new DateTime(1920, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 1,
                            Resume = "Rassemble quatorze nouvelles policières mettant en scène le détective Parker Pyne, professeur de bonheur, prêt à tout pour rendre ses clients heureux.",
                            Subject_Id = 1,
                            Title = "Parker Pyne enquête"
                        },
                        new
                        {
                            Id = 15,
                            Available = true,
                            ISBN = "9782765076803",
                            Price = 60m,
                            Promo = true,
                            PublishedDate = new DateTime(2121, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher_Id = 2,
                            Resume = "La cinquième édition de cet ouvrage expose de manière concrète et concise les grands thèmes de la gestion des ressources humaines en tenant compte d’une préoccupation actuelle: la pénurie de main-d’oeuvre. Le contenu théorique et pratique, entièrement mis à jour, illustre les diverses stratégies à appliquer dans ce contexte.",
                            Subject_Id = 5,
                            Title = "Supervision gestion des RH"
                        });
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PublisherSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Livre de poche",
                            PublisherSite = "https://www.livredepoche.com/",
                            Speciality = "Policier, Mystère"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chenelière",
                            PublisherSite = "https://www.cheneliere.ca/",
                            Speciality = "Études supérieures"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ADA",
                            PublisherSite = "https://www.ada-inc.com/",
                            Speciality = "jeunesse, fantastique"
                        });
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Policier"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Biographie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Collégial-universitaire"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fantastique"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Horreur"
                        });
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.Author", b =>
                {
                    b.HasOne("CrazyBooks_Models.Models.AuthorDetail", "AuthorDetail")
                        .WithOne("Author")
                        .HasForeignKey("CrazyBooks_Models.Models.Author", "AuthorDetail_Id");

                    b.Navigation("AuthorDetail");
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.AuthorBook", b =>
                {
                    b.HasOne("CrazyBooks_Models.Models.Author", "Author")
                        .WithMany("AuthorsBooks")
                        .HasForeignKey("Author_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrazyBooks_Models.Models.Book", "Book")
                        .WithMany("AuthorsBooks")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.Book", b =>
                {
                    b.HasOne("CrazyBooks_Models.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("Publisher_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrazyBooks_Models.Models.Subject", "Subject")
                        .WithMany("Books")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.Author", b =>
                {
                    b.Navigation("AuthorsBooks");
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.AuthorDetail", b =>
                {
                    b.Navigation("Author");
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.Book", b =>
                {
                    b.Navigation("AuthorsBooks");
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CrazyBooks_Models.Models.Subject", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
